---
  el:
    hosts:
      elasticsearch:
        ansible_connection: ssh
        ansible_host: 10.0.1.2 
        ansible_user: vagrant
  
  kb:
    hosts:
      kibana:
        ansible_connection: ssh
        ansible_host: 10.0.1.3 
        ansible_user: vagrant